create table important_dates
(
    id                   integer generated by default as identity
        constraint important_dates_pk
            primary key,
    telegram_id          integer
        constraint important_dates_users_telegram_id_fk
            references users
            on delete set null,
    partner_id           integer
        constraint important_dates_users_telegram_id_fk_2
            references users
            on delete set null,
    title                varchar(256) default 'Важная дата' not null,
    date                 date                               not null,
    is_active            bool         default true          not null,
    last_notification_at timestamp,
    notify_before_days   integer      default 7             not null
);