--
-- PostgreSQL database cluster dump
--

\restrict h9IO7Ccwb0ybb9IB0cxwdUKz2bx2RACaHMddZ24l9KDro8PLAUTKGlQPBsD4LHt

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:+Z4XHfEYjFhB8+WUGUB5wg==$FnnLA3o7rXreue+wtTNvkGUqKtKXo+HjEJg3nEGsoXA=:0h75hIK/xgZQmybIfrFdpb3gJf4vXDPbBhxDkStcpJk=';

--
-- User Configurations
--








\unrestrict h9IO7Ccwb0ybb9IB0cxwdUKz2bx2RACaHMddZ24l9KDro8PLAUTKGlQPBsD4LHt

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict 4NC5PjLtlEIoIqkiAaonOcO5DbTd1v9D45y85IGsdJ9S5BUFIVRcQoTIUDGOQn2

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict 4NC5PjLtlEIoIqkiAaonOcO5DbTd1v9D45y85IGsdJ9S5BUFIVRcQoTIUDGOQn2

--
-- Database "fmlbot" dump
--

--
-- PostgreSQL database dump
--

\restrict IPsutDcRMhoWes9YVk9HFgEtcT99UgN0V5ElMT2OVgev1busf4enyosKmylhVKH

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: fmlbot; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE fmlbot WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE fmlbot OWNER TO postgres;

\unrestrict IPsutDcRMhoWes9YVk9HFgEtcT99UgN0V5ElMT2OVgev1busf4enyosKmylhVKH
\connect fmlbot
\restrict IPsutDcRMhoWes9YVk9HFgEtcT99UgN0V5ElMT2OVgev1busf4enyosKmylhVKH

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: compliments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compliments (
                                    text text DEFAULT ''::character varying NOT NULL,
                                    id integer NOT NULL,
                                    is_sent boolean DEFAULT false NOT NULL,
                                    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.compliments OWNER TO postgres;

--
-- Name: compliments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.compliments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: important_dates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.important_dates (
                                        id integer NOT NULL,
                                        user_id bigint,
                                        partner_id bigint,
                                        title character varying(256) DEFAULT 'Важная дата'::character varying NOT NULL,
                                        date date NOT NULL,
                                        is_active boolean DEFAULT true NOT NULL,
                                        last_notification_at timestamp without time zone,
                                        notify_before_days integer DEFAULT 7 NOT NULL,
                                        created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.important_dates OWNER TO postgres;

--
-- Name: important_dates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.important_dates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.important_dates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schema_migrations (
                                          version bigint NOT NULL,
                                          dirty boolean NOT NULL
);


ALTER TABLE public.schema_migrations OWNER TO postgres;

--
-- Name: user_compliment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_compliment (
                                        id integer NOT NULL,
                                        user_id bigint,
                                        compliment_id integer
);


ALTER TABLE public.user_compliment OWNER TO postgres;

--
-- Name: user_compliment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_compliment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_compliment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: user_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_config (
                                    id integer NOT NULL,
                                    daily_message_time time without time zone DEFAULT '12:00:00'::time without time zone NOT NULL,
                                    max_compliment_count integer DEFAULT 1 NOT NULL,
                                    user_id bigint DEFAULT 0 NOT NULL,
                                    compliment_count integer DEFAULT 0 NOT NULL,
                                    last_compliment_at timestamp with time zone,
                                    compliment_token_bucket integer DEFAULT 2 NOT NULL,
                                    last_bucket_update timestamp with time zone DEFAULT now() NOT NULL,
                                    CONSTRAINT check_compliment_token_bucket CHECK (((compliment_token_bucket >= 0) AND (compliment_token_bucket <= 2)))
);


ALTER TABLE public.user_config OWNER TO postgres;

--
-- Name: user_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              username character varying(255) NOT NULL,
                              user_id bigint NOT NULL,
                              state character varying(64) DEFAULT ''::character varying NOT NULL,
                              partner_id bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: compliments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compliments (text, id, is_sent, created_at) FROM stdin;
привет дура	1	f	2025-12-23 23:42:55.473701
хуй	2	f	2025-12-23 23:43:14.79937
Соси	3	t	2025-12-24 14:10:50.052439
У тебя сочная жопа	4	t	2025-12-24 14:11:49.137482
Иди в пень. С любовью	5	t	2025-12-24 14:13:18.62751
Ты самый самый большой мой подарочек❤️❤️❤️	6	t	2025-12-24 18:17:26.197589
Ты самый самый лучший 💋	10	t	2026-01-02 13:04:21.492431
Просто обожаю тебя, жить без тебя не могу	7	t	2025-12-24 18:17:48.707412
Как же я тебя люблююююююю❤️	8	t	2025-12-24 18:18:13.327396
Ты самый лучший парень на свете	11	t	2026-01-04 20:30:32.660807
Попа у тебя просто шикарная, конечно	9	t	2025-12-24 18:19:00.265318
Ты мой самый родной и любимый мальчик ❤️❤️❤️	14	t	2026-01-21 23:06:41.300881
Вредина моя\nЛюблю тебя безумно💋❤️‍🔥	12	t	2026-01-04 21:40:30.806093
Старый пень 💋	16	t	2026-01-22 15:17:33.824579
Ты мое солнышко ❤️💋	13	t	2026-01-21 17:37:40.354042
Ты мой самый родной человек💋❤️	18	t	2026-02-12 09:51:33.26474
КАК ЖЕ Я ТЕБЯ ОБОЖАЮ АААААА\nПРОСТО СЪЕЛ БЫ ТЕБЯ😇😇😇	15	t	2026-01-22 15:16:38.176613
У тебя все получится ❤️❤️❤️	19	t	2026-02-12 09:51:51.993407
ТЫ МОЙ СЛАДЕНЬКИЙ МАЛЕНЬКИЙ МИЛЕНЬКИЙ КОТИИК	21	t	2026-02-16 18:51:45.743971
Я безумно ценю каждое мгновение с тобой❤️❤️💋	20	t	2026-02-16 00:42:53.965896
Если ты это читаешь, то знай, что я сейчас думаю о тебе и сильно скучаю🥲	24	t	2026-02-16 21:36:37.975847
Я ужасно соскучилась по тебе ❤️😭❤️😭❤️	28	t	2026-02-17 06:02:21.126059
Ты самый умный, самый сильный,  самый ласковый,  самый самый ❤️💋❤️💋❤️💋❤️💋❤️💋❤️	29	t	2026-02-17 06:02:58.096841
Я так сильно тебя люблю, ты даже не представляешь насколько сильно...	25	t	2026-02-16 21:36:55.98472
Я ТЕБЯ ЛЮБЛЮ БОЛЬШЕГО ВСЕГО НА СВЕТЕ ❤️💋❤️💋💋❤️💋❤️	31	t	2026-02-17 12:46:15.960458
Ты самая самая самая красивая, милая, прекрасная девушка во вселенной	26	t	2026-02-16 21:37:51.055295
Каждый день благодарю жизнь за то, что встретил тебя💋💋💋💋	27	t	2026-02-16 21:41:05.745277
Ты мой самый родной человечек. Жить без тебя не могу ❤️💋❤️💋❤️	32	t	2026-02-17 12:46:42.688319
А что за красавчик нажал кнопку 😍😍😍	33	t	2026-02-17 12:46:58.612466
Улыбнись. Ты же самая прекрасная девочка во вселенной😍	34	t	2026-02-18 09:32:12.082518
Каждый раз, когда я тебя вижу, я думаю о том, как мне повезло❤️	35	t	2026-02-18 09:34:36.284786
Ты мой самый большой подарок от жизни. Я безумно счастлива с тобой ❤️💋❤️💋❤️💋❤️💋❤️	36	t	2026-02-18 09:38:32.293802
Скинь письку	37	t	2026-02-18 09:38:43.248176
Хочу на ручки 😭😭❤️	38	t	2026-02-18 09:41:58.114072
прив	39	f	2026-03-03 20:10:35.336961
У тебя обязательно все получится.  Я в тебя верю ❤️💋❤️	40	t	2026-03-04 09:13:51.425184
Ты мой самый самый дорогой человечек ❤️❤️💋💋	48	t	2026-03-25 18:03:03.191119
А я тебя люблюююю❤️‍🔥\nБезумно сильно	49	t	2026-03-25 18:04:07.659354
Ты мой самый крутой мальчик, с самыми крутыми правами ❤️💋❤️💋❤️	52	t	2026-04-17 15:16:36.238621
Ты жопка	53	t	2026-04-17 15:16:52.633873
Ты мое сокровище ❤️💋❤️💋❤️💋❤️	54	t	2026-04-17 15:17:09.791904
Скинь попу	56	f	2026-04-20 18:56:43.967598
Хочу тебя безумно сильно ❤️‍🔥❤️‍🔥	60	f	2026-05-05 11:33:49.495787
Ты самая прекрасная девушка в мире❤️💋	61	f	2026-05-05 11:33:57.189479
\.


--
-- Data for Name: important_dates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.important_dates (id, user_id, partner_id, title, date, is_active, last_notification_at, notify_before_days, created_at) FROM stdin;
2	\N	\N	Первый запуск бота	2025-12-24	t	2025-12-24 12:00:00.026886	0	2025-12-23 23:10:14.020632
3	899438261	\N	Зачет по Проектной Деятельности	2025-12-24	t	2025-12-24 12:00:00.026886	0	2025-12-23 23:22:33.177053
8	787961862	1099757698	Начало отношений	2024-12-24	t	\N	0	2025-12-24 14:19:19.065143
6	736839539	\N	день пизды	2025-12-25	t	2025-12-25 12:00:00.037246	0	2025-12-23 23:44:33.492137
4	899438261	\N	Проектный семинар дура	2025-12-26	t	2025-12-26 12:00:00.000349	1	2025-12-23 23:26:25.516532
5	899438261	\N	Проектный семинар последняя попытка в этом году дурааа	2025-12-27	t	2025-12-27 12:00:00.003352	1	2025-12-23 23:27:06.118243
11	787961862	1099757698	100к в тг	2026-02-15	t	\N	0	2026-02-16 17:28:43.752113
14	\N	\N	Адададмд	2013-06-17	t	\N	3	2026-02-17 18:39:27.543893
15	853752338	\N	офер в ядро	2026-03-03	t	\N	7	2026-03-03 20:41:13.689371
17	787961862	1099757698	Др тик тока	2026-04-09	t	2026-04-09 12:00:00.039965	0	2026-04-08 21:15:24.880102
13	787961862	1099757698	Первый запуск бота	2025-12-24	t	\N	0	2026-02-17 18:35:13.661156
\.


--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schema_migrations (version, dirty) FROM stdin;
19	f
\.


--
-- Data for Name: user_compliment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_compliment (id, user_id, compliment_id) FROM stdin;
1	736839539	1
2	736839539	2
3	1099757698	3
4	1099757698	4
5	1099757698	5
6	787961862	6
7	787961862	7
8	787961862	8
9	787961862	9
10	1099757698	10
11	1099757698	11
12	787961862	12
13	787961862	13
14	1099757698	14
15	787961862	15
16	1099757698	16
18	1099757698	18
19	1099757698	19
20	787961862	20
21	1099757698	21
24	787961862	24
25	787961862	25
26	787961862	26
27	787961862	27
28	1099757698	28
29	1099757698	29
31	1099757698	31
32	1099757698	32
33	1099757698	33
34	787961862	34
35	787961862	35
36	1099757698	36
37	1099757698	37
38	1099757698	38
39	853752338	39
40	1099757698	40
48	787961862	48
49	787961862	49
52	1099757698	52
53	1099757698	53
54	1099757698	54
56	787961862	56
60	787961862	60
61	787961862	61
\.


--
-- Data for Name: user_config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_config (id, daily_message_time, max_compliment_count, user_id, compliment_count, last_compliment_at, compliment_token_bucket, last_bucket_update) FROM stdin;
1	12:00:00	1	853752338	0	\N	2	2026-05-21 21:00:00.104751+00
3	12:00:00	1	899438261	0	\N	2	2026-05-21 21:00:00.104751+00
4	12:00:00	1	736839539	0	\N	2	2026-05-21 21:00:00.104751+00
9	12:00:00	1	819898117	0	\N	2	2026-05-21 21:00:00.104751+00
8	12:00:00	4	787961862	0	2026-04-17 15:15:55.719439+00	2	2026-05-21 21:00:00.104751+00
7	12:00:00	5	1099757698	0	2026-04-18 13:35:26.61326+00	2	2026-05-21 21:00:00.104751+00
12	12:00:00	1	6540249374	0	\N	2	2026-05-21 21:00:00.104751+00
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (username, user_id, state, partner_id) FROM stdin;
radmirr0r	899438261		0
Waycooler1	787961862		1099757698
Waycooler2	6540249374		0
senya_kkkkkkk	1099757698		787961862
penkovgd	853752338	awaiting_title_important_date	0
	7263930178		0
murat0r	736839539		0
InFaGo1	819898117		0
\.


--
-- Name: compliments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compliments_id_seq', 61, true);


--
-- Name: important_dates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.important_dates_id_seq', 18, true);


--
-- Name: user_compliment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_compliment_id_seq', 61, true);


--
-- Name: user_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_config_id_seq', 12, true);


--
-- Name: compliments compliments_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliments
    ADD CONSTRAINT compliments_pk PRIMARY KEY (id);


--
-- Name: important_dates important_dates_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.important_dates
    ADD CONSTRAINT important_dates_pk PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: user_compliment user_compliment_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_compliment
    ADD CONSTRAINT user_compliment_pk PRIMARY KEY (id);


--
-- Name: user_config user_config_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_config
    ADD CONSTRAINT user_config_pk PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: user_compliment compliment_id___fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_compliment
    ADD CONSTRAINT compliment_id___fk FOREIGN KEY (compliment_id) REFERENCES public.compliments(id) ON DELETE CASCADE;


--
-- Name: important_dates important_dates_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.important_dates
    ADD CONSTRAINT important_dates_users_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: important_dates important_dates_users_user_id_fk_2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.important_dates
    ADD CONSTRAINT important_dates_users_user_id_fk_2 FOREIGN KEY (partner_id) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: user_config user_config_users_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_config
    ADD CONSTRAINT user_config_users_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_compliment user_id___fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_compliment
    ADD CONSTRAINT user_id___fk FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict IPsutDcRMhoWes9YVk9HFgEtcT99UgN0V5ElMT2OVgev1busf4enyosKmylhVKH

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict njrPGrnDqTzFFRqaRgVcfh7eImSMlMhJDIW0ehCArI3Ux650VpuCIAgSlpnRlyf

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict njrPGrnDqTzFFRqaRgVcfh7eImSMlMhJDIW0ehCArI3Ux650VpuCIAgSlpnRlyf

--
-- PostgreSQL database cluster dump complete
--

