create table users
(
    username         varchar(255) not null,
    telegram_id      bigint       not null
        primary key,
    state            varchar(64)  default ''::character varying not null,
    partner_username varchar(255) default ''::character varying not null
);

create table compliments
(
    text    text    default ''::character varying not null,
    id      integer generated by default as identity
        constraint compliments_pk
            primary key,
    is_sent boolean default false not null
);

create table user_compliment
(
    id            integer generated by default as identity
        constraint user_compliment_pk
            primary key,
    telegram_id   bigint
        constraint telegram_id___fk
            references users,
    compliment_id integer
        constraint compliment_id___fk
            references compliments
);