// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWCrxlmEnd5RD5lIDRNMFDDae0P3jakI',
    appId: '1:901518464577:web:11af35d19dcbc8f49618c0',
    messagingSenderId: '901518464577',
    projectId: 'fmlbot-4be53',
    authDomain: 'fmlbot-4be53.firebaseapp.com',
    storageBucket: 'fmlbot-4be53.firebasestorage.app',
    measurementId: 'G-PXTRHR55W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdfp2gbaXaixoANTb-HJ6Apt-1e4V8S8',
    appId: '1:901518464577:android:1921d8e2fec542b39618c0',
    messagingSenderId: '901518464577',
    projectId: 'fmlbot-4be53',
    storageBucket: 'fmlbot-4be53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnU31KL6ig3Gs_TAD-p2ftozPPiM-ByQ',
    appId: '1:901518464577:ios:59b6e46c310beb2e9618c0',
    messagingSenderId: '901518464577',
    projectId: 'fmlbot-4be53',
    storageBucket: 'fmlbot-4be53.firebasestorage.app',
    iosBundleId: 'com.example.fmlApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQnU31KL6ig3Gs_TAD-p2ftozPPiM-ByQ',
    appId: '1:901518464577:ios:59b6e46c310beb2e9618c0',
    messagingSenderId: '901518464577',
    projectId: 'fmlbot-4be53',
    storageBucket: 'fmlbot-4be53.firebasestorage.app',
    iosBundleId: 'com.example.fmlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDWCrxlmEnd5RD5lIDRNMFDDae0P3jakI',
    appId: '1:901518464577:web:6ad8f4878ff7a2139618c0',
    messagingSenderId: '901518464577',
    projectId: 'fmlbot-4be53',
    authDomain: 'fmlbot-4be53.firebaseapp.com',
    storageBucket: 'fmlbot-4be53.firebasestorage.app',
    measurementId: 'G-ERLBZ9V8TJ',
  );
}
