create table user_config
(
    id               integer generated by default as identity
        constraint user_config_pk
            primary key,
    compliment_time  time    default '12:00:00' not null,
    compliment_count integer default 1          not null
);